# reach needs some information about the robot
robot_description_file: 
  package: "moveit_resources_fanuc_description"
  file: "urdf/fanuc.urdf"
robot_description_semantic_file: 
  package: "moveit_resources_fanuc_moveit_config"
  file: "config/fanuc.srdf"
robot_description_kinematics_file:
  package: "moveit_resources_fanuc_moveit_config"
  file: config/kinematics.yaml
robot_description_joint_limits_file:
  package: "moveit_resources_fanuc_moveit_config"
  file: "config/joint_limits.yaml"
config_file: 
  package: "path_projection"
  file: "config/reach_config_fanuc.yaml"
results_dir:
  package: "path_projection"
  file: "output/results"
config_name: "fanuc"

# Specifying the base link name of the robot model is used for creating a virtual joint between world and robot_base_frame
# Don't use this if you already know what you're doing 
robot_base_frame: "base_link"
robot_pose: 
  translation: [0.0, 0.0, 0.0]
  rotation_rpy: [0.0, 0.0, 0.0]